apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: weather-station5
  name: weather-station5
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weather-station5
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: weather-station5
    spec:
      containers:
        - args:
            - "5"
          image: weather-station
          name: weather-station5
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
