apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rain-trigger
  name: rain-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rain-trigger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: rain-trigger
    spec:
      containers:
        - image: rain-trigger
          name: rain-trigger
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
