version: '3'
services:
  kafka:
    image: 'bitnami/kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  elastic-kibana:
    image: nshou/elasticsearch-kibana
    ports:
      - '5601:5601'
      - '9200:9200'
    environment:
      - SSL_MODE=false

  weather-station0:
    image: weather-station
    command: [ "0" ]
    depends_on:
      - kafka

  weather-station1:
    image: weather-station
    command: [ "1", "52.52", "13.41" ]
    depends_on:
      - kafka

  weather-station2:
    image: weather-station
    command: [ "2" ]
    depends_on:
      - kafka

  weather-station3:
    image: weather-station
    command: [ "3" ]
    depends_on:
      - kafka

  weather-station4:
    image: weather-station
    command: [ "4" ]
    depends_on:
      - kafka

  weather-station5:
    image: weather-station
    command: [ "5" ]
    depends_on:
      - kafka

  weather-station6:
    image: weather-station
    command: [ "6" ]
    depends_on:
      - kafka

  weather-station7:
    image: weather-station
    command: [ "7" ]
    depends_on:
      - kafka

  weather-station8:
    image: weather-station
    command: [ "8" ]
    depends_on:
      - kafka

  weather-station9:
    image: weather-station
    command: [ "9" ]
    depends_on:
      - kafka

  rain-trigger:
    image: rain-trigger
    depends_on:
      - kafka

  central-station:
    image: central-station
    depends_on:
      - kafka
      - elastic-kibana
    volumes:
      - ../archived_data:/app/archived_data
